"""Geometry helpers for the AprilTag VisionTracker preview.

Image coordinates use OpenCV's convention (x right, y down). Map coordinates
use the project convention (x right/east, z up/north) in millimetres.
"""

from __future__ import annotations

import math
from collections.abc import Sequence

import cv2
import numpy as np


def _point2(value: Sequence[float], name: str) -> np.ndarray:
    point = np.asarray(value, dtype=np.float64)
    if point.shape != (2,) or not np.all(np.isfinite(point)):
        raise ValueError(f"{name} must contain two finite numbers")
    return point


def _corners4(corners: Sequence[Sequence[float]]) -> np.ndarray:
    value = np.asarray(corners, dtype=np.float64)
    if value.shape != (4, 2) or not np.all(np.isfinite(value)):
        raise ValueError("corners must have shape (4, 2) with finite values")
    return value


def normalize_signed_degrees(angle_degrees: float) -> float:
    """Normalize an angle to [-180, 180)."""

    return (float(angle_degrees) + 180.0) % 360.0 - 180.0


def tag_front_midpoint(
    corners: Sequence[Sequence[float]],
    front_edge: Sequence[int] = (2, 3),
) -> np.ndarray:
    """Return the midpoint of the configured physical front edge of a tag.

    For an upright tag generated by the current Limelight PDF, pupil_apriltags
    reports corners 2 and 3 along the top edge. Mount that edge toward the
    vehicle's physical front, or change ``front_edge`` in the JSON config.
    """

    points = _corners4(corners)
    edge = tuple(int(index) for index in front_edge)
    if len(edge) != 2 or any(index < 0 or index > 3 for index in edge):
        raise ValueError("front_edge must contain two corner indices from 0 to 3")
    if edge[0] == edge[1]:
        raise ValueError("front_edge corner indices must be different")
    return (points[edge[0]] + points[edge[1]]) * 0.5


def image_heading_degrees(
    center: Sequence[float], front_point: Sequence[float]
) -> float:
    """Return image-plane heading with 0 right and positive counter-clockwise."""

    origin = _point2(center, "center")
    front = _point2(front_point, "front_point")
    delta = front - origin
    if np.linalg.norm(delta) <= 1e-9:
        raise ValueError("center and front_point must be different")
    return normalize_signed_degrees(math.degrees(math.atan2(-delta[1], delta[0])))


def fit_pixel_to_map_homography(
    pixel_points: Sequence[Sequence[float]],
    map_points_mm: Sequence[Sequence[float]],
    ransac_threshold_mm: float = 10.0,
) -> tuple[np.ndarray, np.ndarray]:
    """Fit a planar pixel -> (x_mm, z_mm) homography.

    Four points use a direct fit. Five or more points use RANSAC so that an
    incorrectly measured or decoded reference point can be rejected.
    """

    source = np.asarray(pixel_points, dtype=np.float64)
    target = np.asarray(map_points_mm, dtype=np.float64)
    if source.ndim != 2 or source.shape[1:] != (2,):
        raise ValueError("pixel_points must have shape (N, 2)")
    if target.shape != source.shape:
        raise ValueError("map_points_mm must have the same shape as pixel_points")
    if len(source) < 4:
        raise ValueError("at least four reference points are required")
    if not np.all(np.isfinite(source)) or not np.all(np.isfinite(target)):
        raise ValueError("homography points must all be finite")
    threshold = float(ransac_threshold_mm)
    if not math.isfinite(threshold) or threshold <= 0.0:
        raise ValueError("RANSAC threshold must be positive and finite")

    if len(source) > 4:
        # With only five or six references, RANSAC can lock onto an exact
        # four-point subset and never form a larger consensus even when one
        # direct fit keeps every reference inside the configured threshold.
        # Accept that deterministic fit only when *all* anchors satisfy the
        # same strict threshold; otherwise retain RANSAC's bad-anchor defense.
        direct_homography, _ = cv2.findHomography(source, target, method=0)
        if direct_homography is not None and np.all(np.isfinite(direct_homography)):
            projected = cv2.perspectiveTransform(
                source.reshape(-1, 1, 2), direct_homography
            ).reshape(-1, 2)
            direct_errors = np.linalg.norm(projected - target, axis=1)
            if np.all(np.isfinite(direct_errors)) and np.all(
                direct_errors <= threshold
            ):
                return direct_homography, np.ones(len(source), dtype=bool)

    method = cv2.RANSAC if len(source) > 4 else 0
    homography, mask = cv2.findHomography(
        source,
        target,
        method=method,
        ransacReprojThreshold=threshold,
    )
    if homography is None or not np.all(np.isfinite(homography)):
        raise ValueError("reference points could not produce a valid homography")

    if mask is None:
        mask = np.ones((len(source), 1), dtype=np.uint8)
    return homography, mask.reshape(-1).astype(bool)


def project_point(
    homography: Sequence[Sequence[float]], point: Sequence[float]
) -> np.ndarray:
    """Project one image point through a 3x3 homography."""

    matrix = np.asarray(homography, dtype=np.float64)
    if matrix.shape != (3, 3) or not np.all(np.isfinite(matrix)):
        raise ValueError("homography must be a finite 3x3 matrix")
    source = _point2(point, "point")
    homogeneous = matrix @ np.array([source[0], source[1], 1.0])
    denominator = float(homogeneous[2])
    scale = max(1.0, float(np.linalg.norm(matrix, ord=np.inf)))
    if not math.isfinite(denominator) or abs(denominator) <= 1e-12 * scale:
        raise ValueError("homography projection is on or near the projective horizon")
    projected = homogeneous[:2] / denominator
    if not np.all(np.isfinite(projected)):
        raise ValueError("homography projection produced a non-finite point")
    return projected


def tag_center_to_robot_origin(
    tag_x_mm: float,
    tag_z_mm: float,
    robot_heading_deg: float,
    forward_offset_mm: float,
    left_offset_mm: float,
) -> tuple[float, float]:
    """Translate the detected tag center to the Server AGV reference point.

    The offset vector is measured on the chassis from the ID 0 tag center to
    the desired robot origin. ``forward`` follows the robot heading and
    ``left`` is positive 90 degrees counter-clockwise from it.
    """

    values = np.asarray(
        [
            tag_x_mm,
            tag_z_mm,
            robot_heading_deg,
            forward_offset_mm,
            left_offset_mm,
        ],
        dtype=np.float64,
    )
    if not np.all(np.isfinite(values)):
        raise ValueError("robot-origin transform values must be finite")
    heading_rad = math.radians(float(robot_heading_deg))
    cos_heading = math.cos(heading_rad)
    sin_heading = math.sin(heading_rad)
    x_mm = (
        float(tag_x_mm)
        + float(forward_offset_mm) * cos_heading
        - float(left_offset_mm) * sin_heading
    )
    z_mm = (
        float(tag_z_mm)
        + float(forward_offset_mm) * sin_heading
        + float(left_offset_mm) * cos_heading
    )
    return x_mm, z_mm


def tag_axis_point(
    tag_homography: Sequence[Sequence[float]],
    local_axis_tip: Sequence[float] = (0.0, -0.8),
) -> np.ndarray:
    """Project a canonical tag-axis point into image pixels.

    ``pupil_apriltags`` maps the canonical top of a decoded tag toward negative
    local Y, so (0, -0.8) points toward the top edge without touching it. This
    remains correct under perspective, unlike averaging two projected corners.
    """

    return project_point(tag_homography, local_axis_tip)


def map_pose_from_pixel_axis(
    homography: Sequence[Sequence[float]],
    center: Sequence[float],
    front_pixel: Sequence[float],
) -> tuple[float, float, float]:
    """Convert a pixel center/front-axis pair to map pose."""

    center_map = project_point(homography, center)
    front_map = project_point(homography, front_pixel)
    delta = front_map - center_map
    if np.linalg.norm(delta) <= 1e-9:
        raise ValueError("projected center and front point must be different")
    heading = normalize_signed_degrees(math.degrees(math.atan2(delta[1], delta[0])))
    return float(center_map[0]), float(center_map[1]), heading


def map_pose_from_tag(
    homography: Sequence[Sequence[float]],
    center: Sequence[float],
    corners: Sequence[Sequence[float]],
    front_edge: Sequence[int] = (2, 3),
) -> tuple[float, float, float]:
    """Convert a detected tag to map x_mm, z_mm, and heading degrees."""

    front_pixel = tag_front_midpoint(corners, front_edge)
    return map_pose_from_pixel_axis(homography, center, front_pixel)
